# Generated by Django 4.2.6 on 2023-11-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_products_cart_productss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='productss',
            new_name='products',
        ),
    ]
